service: test-engine-service
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: production
  region: eu-central-1
  memorySize: 128
custom:
 wsgi:
   app: src/app.app
   packRequirements: false
 pythonRequirements:
    pythonBin: python3
plugins:
  - serverless-wsgi
  - serverless-python-requirements
functions:
  app:
    handler: wsgi_handler.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true